### ISSUE TITLE
Wrong position of window notifications in Window Mode

### ISSUE THREAD

**Issue by dualbios** [raflop/ToastNotifications#46] opened 2017-08-18 08:13 UTC
![n](https://user-images.githubusercontent.com/22467407/29450163-36b31d94-8406-11e7-9321-6fe7625e4ca4.png)

**Comment by rileybwesley** [comment] 2017-08-22 18:48
I am experiencing the same. Any resolution?

**Comment by dualbios** [comment] 2017-08-22 19:41
Both monitors has the same resolution but the resolution is 125%.

**Comment by dualbios** [comment] 2017-08-22 19:43
I will investigate it soon. I think the problem is in using the wrong screen size method.

**Comment by b-mi** [comment] 2017-08-22 20:25
I tried it on system with two displays, window 10, resolutiion 100% and 100%, 100% and 125%, 125% and 125% and positions was correct. Need more informations about problem.
http://i.imgur.com/U3DDetY.png

**Comment by dualbios** [comment] 2017-08-23 09:27
there is reproduced from my side.
the "shift" effect become bigger when window moved to right side of monitor.
if main window placed near left side then it looks ok.
i will investigate.

**Comment by b-mi** [comment] 2017-08-24 20:35
I cannot reproduce this problem on two displays. I moved window on various location on displays and I created messages - without shift. What version of windows do you use?

**Comment by raflop** [comment] 2017-08-25 17:01
Hi, this bug exist, this is related with dpi and calculations between windows pixels + wpf virtual pixels and dpi. And to be honest I have no idea how to fix that, I spend a lot of time on that problem.  Its related to #33

This should happen only with WindowPositionProvider

**Comment by b-mi** [comment] 2017-09-09 05:15
.net framework 4.6.2 has this update, which may help with problem with DPI:

_"Per-monitor DPI To support the recent proliferation of high-DPI and hybrid-DPI environments for WPF apps, WPF in the .NET Framework 4.6.2 enables per-monitor awareness. See the samples and developer guide on GitHub for more information about how to enable your WPF app to become per-monitor DPI aware."_

ToastNotification can be compiled to .net framework 4.6.2. May be help.

**Comment by raflop** [comment] 2017-09-09 11:11
Hey,

Unfortunatelly it's not an option to upgrade ToastNotifications to .NET 4.6.2, because there are already existing projects (especialy mine :) ) which uses this library, and they cannot upgrade .NET framework because of some restrictions.

I think there must be a way to do these calculations, maybe there is a way to extract formula from .NET 4.6.2 :)

Thanks for help & Best regards

**Comment by ZmorzynskiK** [comment] 2017-10-19 19:12
I might have found a solution, please check #57

**Comment by raflop** [comment] 2017-10-19 20:10
@ZmorzynskiK fixed that, in my test it worked in different dpi and resolutions. and mixed configurations on two displays, dragging window from one to another.

Thank you for help, this is released in nuget v2.2.5

**Closed by raflop** 2017-10-19 20:10 UTC
Labels: bug, help wanted
